NAME = ScavTrap

SRC = main.cpp ClapTrap.cpp ScavTrap.cpp

all : $(NAME)

$(NAME):$(SRC)
	c++ -Wall -Wextra -Werror -std=c++98 $(SRC) -o ScavTrap
clean:
	rm -rf ScavTrap
fclean:
	rm -rf ScavTrap
re: fclean all
