NAME = FragTrap

SRC = main.cpp ClapTrap.cpp ScavTrap.cpp FragTrap.cpp

all : $(NAME)

$(NAME):$(SRC)
	c++ -Wall -Wextra -Werror -std=c++98 $(SRC) -o FragTrap
clean:
	rm -rf FragTrap
fclean:
	rm -rf FragTrap
re: fclean all
